package com.axsos.Life.models;
import jakarta.persistence.*; import java.time.LocalTime; import static com.axsos.Life.models.Enums.*;
@Entity @Table(name="health_profiles") public class HealthProfile extends BaseEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @OneToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="user_id",nullable=false,unique=true) private User user;
 private Double height; private Double weight; private Double targetWeight; private Integer age;
 @Enumerated(EnumType.STRING) private Gender gender; @Column(length=10) private String bloodType;
 @Enumerated(EnumType.STRING) private PrimaryGoal primaryGoal; @Enumerated(EnumType.STRING) private ActivityLevel activityLevel;
 @Column(length=120) private String occupation; private LocalTime workStartTime; private LocalTime workEndTime; private LocalTime sleepTime; private LocalTime wakeTime;
 private boolean pregnant; private boolean eatingDisorderHistory; @Column(length=1000) private String gateNotes; private boolean remindersEnabled=true;
 public Long getId(){return id;} public void setId(Long v){id=v;} public User getUser(){return user;} public void setUser(User v){user=v;} public Double getHeight(){return height;} public void setHeight(Double v){height=v;} public Double getWeight(){return weight;} public void setWeight(Double v){weight=v;} public Double getTargetWeight(){return targetWeight;} public void setTargetWeight(Double v){targetWeight=v;} public Integer getAge(){return age;} public void setAge(Integer v){age=v;} public Gender getGender(){return gender;} public void setGender(Gender v){gender=v;} public String getBloodType(){return bloodType;} public void setBloodType(String v){bloodType=v;} public PrimaryGoal getPrimaryGoal(){return primaryGoal;} public void setPrimaryGoal(PrimaryGoal v){primaryGoal=v;} public ActivityLevel getActivityLevel(){return activityLevel;} public void setActivityLevel(ActivityLevel v){activityLevel=v;} public String getOccupation(){return occupation;} public void setOccupation(String v){occupation=v;} public LocalTime getWorkStartTime(){return workStartTime;} public void setWorkStartTime(LocalTime v){workStartTime=v;} public LocalTime getWorkEndTime(){return workEndTime;} public void setWorkEndTime(LocalTime v){workEndTime=v;} public LocalTime getSleepTime(){return sleepTime;} public void setSleepTime(LocalTime v){sleepTime=v;} public LocalTime getWakeTime(){return wakeTime;} public void setWakeTime(LocalTime v){wakeTime=v;} public boolean isPregnant(){return pregnant;} public void setPregnant(boolean v){pregnant=v;} public boolean isEatingDisorderHistory(){return eatingDisorderHistory;} public void setEatingDisorderHistory(boolean v){eatingDisorderHistory=v;} public String getGateNotes(){return gateNotes;} public void setGateNotes(String v){gateNotes=v;} public boolean isRemindersEnabled(){return remindersEnabled;} public void setRemindersEnabled(boolean v){remindersEnabled=v;}
}
